import os
import pickle
import numpy as np
import tensorflow as tf
import time
from music21 import instrument, note, stream, chord

# Import our custom network builder
from model import create_network

# Temperature / creativity control (default value: 1.0)
# Low temperature (0.5) = more predictable music
# High temperature (1.5) = more creative/random music
TEMPERATURE = float(os.environ.get("TEMPERATURE", 1.0))
NOTE_COUNT = int(os.environ.get("NOTE_COUNT", 500))

def generate_music():
    """ 
    Generate a new music sequence from the trained neural network.
    """
    print(f"Starting music generation with TEMPERATURE = {TEMPERATURE}")
    base_dir = os.path.dirname(os.path.abspath(__file__))
    notes_file = os.path.join(base_dir, "notes.pkl")
    model_path = os.path.join(base_dir, "music_model.h5")
    
    # Gracefully handle missing files
    if not os.path.exists(notes_file) or not os.path.exists(model_path):
        print(f"Error: Required files not found.")
        if not os.path.exists(notes_file): print(" - notes.pkl is missing. Please run preprocess.py first.")
        if not os.path.exists(model_path): print(" - music_model.h5 is missing. Please run train.py first.")
        return 0
        
    print(f"Loading notes from {notes_file}...")
    with open(notes_file, 'rb') as filepath:
        notes = pickle.load(filepath)
        
    pitchnames = sorted(set(item for item in notes))
    n_vocab = len(set(notes))
    
    # Create the model architecture
    print("Rebuilding model architecture...")
    model = create_network(n_vocab)
    
    # Load the weights from the trained model
    print(f"Loading weights from {model_path}...")
    model.load_weights(model_path)
    
    # Prepare mapping functions
    note_to_int = dict((note, number) for number, note in enumerate(pitchnames))
    int_to_note = dict((number, note) for number, note in enumerate(pitchnames))
    
    sequence_length = 100
    network_input = []
    
    # Prepare inputs for starting sequence selection
    for i in range(0, len(notes) - sequence_length, 1):
        sequence_in = notes[i:i + sequence_length]
        network_input.append([note_to_int[char] for char in sequence_in])
        
    if not network_input:
        print("Error: Not enough notes in notes.pkl to create a sequence of length 100.")
        print("Please provide more MIDI files for preprocessing.")
        return 0
        
    # Pick a random starting sequence from the training data
    start_index = np.random.randint(0, len(network_input)-1)
    pattern = network_input[start_index]
    
    print("Random starting sequence selected.")
    print(f"Generating {NOTE_COUNT} new notes by predicting one note at a time...")
    
    prediction_output = []
    
    # Generate requested number of notes
    for note_index in range(NOTE_COUNT):
        # Format the input sequence for the model
        prediction_input = np.reshape(pattern, (1, len(pattern), 1))
        prediction_input = prediction_input / float(n_vocab)
        
        # Predict the next note
        prediction = model.predict(prediction_input, verbose=0)
        
        # Apply temperature sampling instead of greedy np.argmax
        prediction = prediction[0] / TEMPERATURE
        prediction = prediction - np.max(prediction) # For numerical stability
        prediction = np.exp(prediction) / np.sum(np.exp(prediction))
        prediction = prediction / np.sum(prediction) # Ensure probabilities sum precisely to 1
        index = np.random.choice(len(prediction), p=prediction)
        
        # Map predicted integer back to note/chord string
        result = int_to_note[index]
        prediction_output.append(result)
        
        # Feed the output back as input by sliding the window
        pattern.append(index)
        pattern = pattern[1:len(pattern)]
        
        if (note_index + 1) % 50 == 0:
            print(f"Generated {note_index + 1}/{NOTE_COUNT} notes...")
            
    print("Generation complete. Converting sequence to MIDI file...")
    create_midi(prediction_output, base_dir)
    
    # Calculate estimated duration (0.5 quarter notes per generated note @ 120bpm = 0.25 seconds per note)
    estimated_minutes = round((NOTE_COUNT * 0.25) / 60, 2)
    print(f"\noutput.mid saved — {NOTE_COUNT} notes generated (~{estimated_minutes} minutes of music)")
    return NOTE_COUNT

def create_midi(prediction_output, base_dir):
    """ 
    Convert the output from the prediction back to a playable MIDI file.
    """
    offset = 0
    output_notes = []
    
    # Create note and chord objects based on the values generated by the model
    for pattern in prediction_output:
        # If the pattern contains a dot (.) or is numeric -> treat as a Chord
        if ('.' in pattern) or pattern.isdigit():
            notes_in_chord = pattern.split('.')
            notes = []
            for current_note in notes_in_chord:
                new_note = note.Note(int(current_note))
                new_note.storedInstrument = instrument.Piano()
                notes.append(new_note)
            new_chord = chord.Chord(notes)
            new_chord.offset = offset
            output_notes.append(new_chord)
            
        # Otherwise -> treat as a Note
        else:
            new_note = note.Note(pattern)
            new_note.offset = offset
            new_note.storedInstrument = instrument.Piano()
            output_notes.append(new_note)
            
        # Set each note's offset to increment by 0.5 so notes don't stack
        offset += 0.5
        
    # Build a music21 Stream
    midi_stream = stream.Stream(output_notes)
    
    # Write the output Stream as a MIDI file
    output_file = os.path.join(base_dir, "output.mid")
    midi_stream.write('midi', fp=output_file)
    
    print(f"Successfully saved generated music to {output_file}")
    
    # Attempt to convert MIDI to WAV audio
    try:
        from midi2audio import FluidSynth
        wav_file = os.path.join(base_dir, "output.wav")
        print("Attempting to convert output.mid to output.wav using FluidSynth...")
        fs = FluidSynth()
        fs.midi_to_audio(output_file, wav_file)
        print("Audio saved as output.wav")
    except ImportError:
        print("Skipping audio conversion: 'midi2audio' library is not installed.")
        print("To enable MIDI to WAV conversion, install it via: pip install midi2audio")
    except Exception as e:
        print(f"Skipping audio conversion: FluidSynth conversion failed ({e}).")
        print("Note: FluidSynth requires the fluidsynth system executable and a soundfont.")

if __name__ == '__main__':
    try:
        start_time = time.time()
        generate_music()
        elapsed = int(time.time() - start_time)
        print(f"Completed in {elapsed // 60} minutes {elapsed % 60} seconds")
    except Exception as e:
        print(f"Something went wrong: {e}. Please check the README for help.")
